{"uid":"9a1e6bf3ff96bd9a","name":"test_get_auth_right","fullName":"testcases.test_scenario.auth.test_auth#test_get_auth_right","historyId":"69a8f2422cb5dce0680ffaa0b18d3f0d","time":{"start":1758157789409,"stop":1758157789409,"duration":0},"description":"测试获取access_token","descriptionHtml":"<p>测试获取access_token</p>\n","status":"broken","statusMessage":"_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_get_auth_right>>)","statusTrace":"file D:\\GitHub\\aomaker\\mockapitest\\testcases\\test_scenario\\auth\\test_auth.py, line 10\n  @pytest.mark.auth\n  def test_get_auth_right(self):\nE       fixture 'self' not found\n>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nD:\\GitHub\\aomaker\\mockapitest\\testcases\\test_scenario\\auth\\test_auth.py:10","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"auth"},{"name":"parentSuite","value":"testcases.test_scenario.auth"},{"name":"suite","value":"test_auth"},{"name":"host","value":"admin"},{"name":"thread","value":"34480-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"testcases.test_scenario.auth.test_auth"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":["auth"]},"source":"9a1e6bf3ff96bd9a.json","parameterValues":[]}