{"name": "test_get_auth_with_errpassword", "status": "passed", "description": "测试输入错误的password获取access_token", "attachments": [{"name": "LoginForAccessTokenApiLoginTokenPostAPI", "source": "cdf3fb3a-2552-4398-a1d3-3b65adbf57df-attachment.json", "type": "application/json"}, {"name": "log", "source": "507b8797-28f7-4eb1-a2c0-61378d30d255-attachment.txt", "type": "text/plain"}], "start": 1758157789578, "stop": 1758157789594, "uuid": "70845fca-0045-4e62-9ee1-c07efd3de48f", "historyId": "b17f5c6455c02bd06e10535474b56c52", "testCaseId": "53cdce8c0755db7990a2f74be0704d04", "fullName": "testcases.test_scenario.auth.test_auth#test_get_auth_with_errpassword", "labels": [{"name": "tag", "value": "auth"}, {"name": "parentSuite", "value": "testcases.test_scenario.auth"}, {"name": "suite", "value": "test_auth"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "34480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_scenario.auth.test_auth"}]}